backend/CatiLyfe.Backend.Web.Core/Controllers/IndexController.cs
namespace CatiLyfe.Backend.Web.Core.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;

    /// <summary>
    /// The index controller.
    /// </summary>
    [Route("")]
    public class IndexController : Controller
    {
        /// <summary>
        /// The home page.
        /// </summary>
        /// <returns>The view.</returns>
        [HttpGet]
        public ViewResult HomePage()
        {
            return this.View();
        }

        /// <summary>
        /// Redirect to swagger.
        /// </summary>
        /// <returns>The redirect.</returns>
        [HttpGet("api")]
        public RedirectResult Api()
        {
            return this.Redirect("~/swagger");
        }
    }
}

backend/CatiLyfe.Backend.Web.Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/Site.min.css" />
</head>
<body>

    <div class="horizontal-align title">
        <ul class="nav-horizontal horizontal-align">
            <li>@Html.ActionLink("Home", "HomePage", "Index", new { area = "" }, null)</li>
            <li>@Html.ActionLink("API", "Api", "Index", new { area = "" }, null)</li>
        </ul>
    </div>
    <div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Peter and Justin</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>